import Head from "next/head";
import styles from "../styles/Home.module.css";
import MapComponent from "../components/map";
import Shipment from "../components/shipmentPlan";
import Nav from "../components/nav";
const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mapbox Curved Route with Sea Routes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.tiles.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </Head>
      <Nav />
      <main className={styles.main}>
        <MapComponent />
        <div className="w-full p-4 flex">
          <h3 className="font-bold text-base">Shipping Routes</h3>
        </div>
        <Shipment />
      </main>
      <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.js"></script>
      <script src="https://unpkg.com/@turf/turf"></script>
    </div>
  );
};

export default Home;
